language: node_js
node_js:
  - 14.17.0
cache: yarn
before_install:
  - npm i -g npm@7.13.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.10
script:
  - yarn build
  - yarn test
