language: node_js
node_js:
  - 14.3.0
cache: yarn
before_install:
  - npm i -g npm@6.14.5
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
script:
  - yarn build
  - yarn test
